/**
 * Shared API contracts for BFF routes and client islands.
 * Keep this module free of server-only imports.
 */

export const REACTION_TYPES = ["like", "fire", "idea", "question"] as const;
export type ReactionType = (typeof REACTION_TYPES)[number];

/** Four reaction counts, always zero-filled so the UI can render statically. */
export type ReactionCounts = Record<ReactionType, number>;

/** GET /api/reactions/:slug */
export interface ReactionsResponse {
  counts: ReactionCounts;
  /** Reaction types the caller (user or anonymous client) has selected. */
  selected: ReactionType[];
}

/** POST /api/reactions/:slug body */
export interface ReactionVoteBody {
  reaction: ReactionType;
  /** Required for anonymous votes (UUID v4 generated by the browser). */
  client_id?: string;
}

/** GET /api/reactions/totals — site-wide aggregate counts. */
export interface ReactionTotalsResponse {
  totals: ReactionCounts;
}

export type ApiErrorCode =
  | "VALIDATION_ERROR"
  | "POST_NOT_FOUND"
  | "UNAUTHORIZED"
  | "RATE_LIMITED"
  | "SUPABASE_NOT_CONFIGURED"
  | "INTERNAL_ERROR";

export interface ApiErrorBody {
  error: { code: ApiErrorCode; message: string };
}

/** Header carrying the anonymous device id (UUID v4 in localStorage). */
export const CLIENT_ID_HEADER = "x-client-id";

// ─── Analytics ────────────────────────────────────────────────

export const WEB_VITAL_METRICS = ["lcp", "cls", "inp"] as const;
export type WebVitalMetric = (typeof WEB_VITAL_METRICS)[number];

export const WEB_VITAL_RATINGS = ["good", "needs-improvement", "poor"] as const;
export type WebVitalRating = (typeof WEB_VITAL_RATINGS)[number];

export const VIEWPORT_BUCKETS = ["xs", "sm", "md", "lg"] as const;
export type ViewportBucket = (typeof VIEWPORT_BUCKETS)[number];

export const UA_CLASSES = ["mobile", "tablet", "desktop"] as const;
export type UaClass = (typeof UA_CLASSES)[number];

export interface PageviewBody {
  type: "pageview";
  /** Anonymous device UUID — sent in body because sendBeacon cannot set headers. */
  clientId: string;
  path: string;
  referrer: string | null;
  locale: string;
  viewport: ViewportBucket;
  uaClass: UaClass;
}

export interface WebVitalBody {
  type: "web-vital";
  clientId: string;
  path: string;
  metric: WebVitalMetric;
  value: number;
  rating: WebVitalRating;
  /** web-vitals library unique metric instance id (dedup/debug aid). */
  id: string;
}

export type AnalyticsEventBody = PageviewBody | WebVitalBody;

/** GET /api/analytics/summary */
export interface AnalyticsSummaryResponse {
  /** One entry per day with any traffic, ascending. */
  daily: { day: string; pv: number; uv: number }[];
  /** Most viewed articles over 30 days, locale prefixes merged. */
  topPosts: { path: string; views: number }[];
  /** Rating counts per metric, always zero-filled. */
  vitals: Record<WebVitalMetric, Record<WebVitalRating, number>>;
  /** Site-wide reaction counts (reuses reaction_totals). */
  reactions: ReactionCounts;
}
